name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: jankim366/KoXray
          username: '${{ jankim366 }}'
          password: '${{ 9m4g2:3I/3}7!0y[ }}'
